# SPDX-FileCopyrightText: Copyright © duneuro contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-duneuro-exception OR LGPL-3.0-or-later

---

stages:
  - .pre
  - build_and_test

########################
# Common
########################

.common_build:
  stage: build_and_test
  before_script:
    - mkdir -p /duneci/modules
  script:
    - python3 ci_information/resolve_dune_dependencies.py --outputbasedir /duneci/modules
    - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts all
    - ln -sf /duneci/modules/dune-common/bin/dunecontrol /duneci/bin
    - ln -sf /duneci/modules/dune-common/bin/dune-ctest /duneci/bin
    - duneci-standard-test

########################
# Ubuntu 24.04 tests
########################

ubuntu:24.04_gcc-14-23_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  variables:
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: gcc-14-23

ubuntu:24.04_gcc-14-23:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  variables:
    DUNECI_TOOLCHAIN: gcc-14-23

ubuntu:24.04_clang-18-23_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  variables:
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: clang-18-23

ubuntu:24.04_clang-18-23:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  variables:
    DUNECI_TOOLCHAIN: clang-18-23

########################
# Ubuntu 22.04 tests
########################

ubuntu:22.04_gcc-11-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  variables:
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: gcc-11-20

ubuntu:22.04_gcc-11-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  variables:
    DUNECI_TOOLCHAIN: gcc-11-20

ubuntu:22.04_clang-14-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  variables:
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: clang-14-20

ubuntu:22.04_clang-14-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  variables:
    DUNECI_TOOLCHAIN: clang-14-20

########################
# Debian 12 tests
########################

debian:12_gcc-12-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  variables:
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: gcc-12-20

debian:12_gcc-12-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  variables:
    DUNECI_TOOLCHAIN: gcc-12-20

debian:12_clang-14-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  variables:
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: clang-14-20

debian:12_clang-14-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  variables:
    DUNECI_TOOLCHAIN: clang-14-20


########################
# .pre stage tests
########################

# Check spelling
code-spelling-check:
  stage: .pre
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-spelling-check]
  script:
   - codespell
     --ignore-words-list nin,elemente --skip="./.git/logs/*"

# Check licensing
reuse:
  stage: .pre
  image:
    name: docker.io/fsfe/reuse:latest
    entrypoint: [""]
  tags: [duneuroci-license-check]
  script:
    - reuse lint
