---

test-job:
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  before_script:
    - mkdir -p /duneci/modules
  script:
    - python3 ci_information/resolve_dune_dependencies.py --outputbasedir /duneci/modules
    - /duneci/modules/dune-common/bin/dunecontrol
