# SPDX-FileCopyrightText: Copyright © duneuro contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-duneuro-exception OR LGPL-3.0-or-later

---

stages:
  - .pre
  - build_and_test
  - bindings

########################
# Common
########################

.common_build:
  stage: build_and_test
  before_script:
    - mkdir -p /duneci/modules
  script:
    - python3 ci_information/resolve_dune_dependencies.py --outputbasedir /duneci/modules
    - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts all
    - ln -sf /duneci/modules/dune-common/bin/dunecontrol /duneci/bin
    - ln -sf /duneci/modules/dune-common/bin/dune-ctest /duneci/bin
    - duneci-standard-test

.common_python_bindings:
  stage: bindings
  before_script:
    - mkdir -p /duneci/modules
  script:
    - python3 ci_information/resolve_dune_dependencies.py --outputbasedir /duneci/modules
    - python3 ci_information/get_python_bindings.py --outputbasedir /duneci/modules
    - ln -sf /duneci/modules/dune-common/bin/dunecontrol /duneci/bin
    - ln -sf /duneci/modules/dune-common/bin/dune-ctest /duneci/bin
    - dunecontrol --opts=/duneci/dune.opts --builddir=/duneci/modules/build all
    - cd /duneci/modules/build/duneuro-py
    - dune-ctest

variables:
  COMMON_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_MPI=TRUE'

########################
# Ubuntu 24.04 tests
########################

ubuntu:24.04_gcc-14-23_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  tags: [duneuroci-ubuntu24]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS -DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: gcc-14-23

ubuntu:24.04_gcc-14-23:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  tags: [duneuroci-ubuntu24]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: gcc-14-23

ubuntu:24.04_clang-18-23_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  tags: [duneuroci-ubuntu24]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS -DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: clang-18-23

ubuntu:24.04_clang-18-23:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  tags: [duneuroci-ubuntu24]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: clang-18-23

########################
# Ubuntu 22.04 tests
########################

ubuntu:22.04_gcc-11-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  tags: [duneuroci-ubuntu22]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS -DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: gcc-11-20

ubuntu:22.04_gcc-11-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  tags: [duneuroci-ubuntu22]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: gcc-11-20

ubuntu:22.04_clang-14-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  tags: [duneuroci-ubuntu22]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS -DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: clang-14-20

ubuntu:22.04_clang-14-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  tags: [duneuroci-ubuntu22]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: clang-14-20

########################
# Debian 12 tests
########################

debian:12_gcc-12-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-debian12]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS -DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: gcc-12-20

debian:12_gcc-12-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-debian12]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: gcc-12-20

debian:12_clang-14-20_noTBB:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-debian12]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS -DCMAKE_DISABLE_FIND_PACKAGE_TBB=TRUE'
    DUNECI_TOOLCHAIN: clang-14-20

debian:12_clang-14-20:
  extends: .common_build
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-debian12]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: clang-14-20


########################
# Python bindings
########################

ubuntu:24.04_gcc-14-23_python_bindings:
  extends: .common_python_bindings
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  tags: [duneuroci-ubuntu24]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: gcc-14-23

ubuntu:24.04_clang-18-23_python_bindings:
  extends: .common_python_bindings
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  tags: [duneuroci-ubuntu24]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: clang-18-23

ubuntu:22.04_gcc-11-20_python_bindings:
  extends: .common_python_bindings
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  tags: [duneuroci-ubuntu22]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: gcc-11-20

ubuntu:22.04_clang-14-20_python_bindings:
  extends: .common_python_bindings
  image: registry.dune-project.org/docker/ci/ubuntu:22.04
  tags: [duneuroci-ubuntu22]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: clang-14-20

debian:12_gcc-12-20_python_bindings:
  extends: .common_python_bindings
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-debian12]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: gcc-12-20

debian:12_clang-14-20_python_bindings:
  extends: .common_python_bindings
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-debian12]
  variables:
    DUNECI_CMAKE_FLAGS: '$COMMON_CMAKE_FLAGS'
    DUNECI_TOOLCHAIN: clang-14-20

########################
# Matlab bindings
########################

ubuntu:22.04_matlab_r2024b_bindings:
  stage: bindings
  image: 
    name: mathworks/matlab:r2024b
    entrypoint: [""]
  tags: [duneuroci-ubuntu22]
  variables:
#    LD_PRELOAD: '/usr/lib/x86_64-linux-gnu/libstdc++.so.6'
#    Matlab_ROOT_DIR: /opt/matlab/R2024b
#    DUNE_CONTROL_PATH: /home/matlab/dune-modules
    MLM_LICENSE_FILE: $MATLAB_LICENSE_SERVER
#  before_script:
#    - mkdir -p $DUNE_CONTROL_PATH/duneuro
  script:
     - matlab -nodesktop -nosplash -r "disp('Hello World!); exit"
#    - mv -f ./* $DUNE_CONTROL_PATH/duneuro
#    - cd $DUNE_CONTROL_PATH/duneuro
#    - sudo bash ./ci_information/resolve_non_dune_dependencies.sh
#    - python3 ./ci_information/resolve_dune_dependencies.py --outputbasedir $DUNE_CONTROL_PATH
#    - python3 ./ci_information/get_matlab_bindings.py --outputbasedir $DUNE_CONTROL_PATH
#    - $DUNE_CONTROL_PATH/dune-common/bin/dunecontrol --opts=./ci_information/config_release.opts --builddir=$DUNE_CONTROL_PATH/build-release all
#    - cd $DUNE_CONTROL_PATH/build-release/duneuro-matlab
#    - ctest --verbose

########################
# .pre stage tests
########################

# Check spelling
code-spelling-check:
  stage: .pre
  image: registry.dune-project.org/docker/ci/debian:12
  tags: [duneuroci-spelling-check]
  script:
   - codespell
     --ignore-words-list nin,elemente --skip="./.git/*"

# Check licensing
reuse:
  stage: .pre
  image:
    name: docker.io/fsfe/reuse:latest
    entrypoint: [""]
  tags: [duneuroci-license-check]
  script:
    - reuse lint
