# SPDX-FileCopyrightText: Copyright © duneuro contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-duneuro-exception OR LGPL-3.0-or-later

---

stages:
  - .pre
  - build

test-job:
  stage: build
  image: registry.dune-project.org/docker/ci/ubuntu:24.04
  before_script:
    - mkdir -p /duneci/modules
  script:
    - python3 ci_information/resolve_dune_dependencies.py --outputbasedir /duneci/modules
    - /duneci/modules/dune-common/bin/dunecontrol all

reuse:
  stage: .pre
  image:
    name: docker.io/fsfe/reuse:latest
    entrypoint: [""]
  tags: [duneci]
  script:
    - reuse lint
