# SPDX-FileCopyrightText: Copyright © duneuro contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-duneuro-exception OR LGPL-3.0-or-later
################################
# Dune module information file #
################################

#Name of the module
Module: duneuro
Version: 2.6-dev
Maintainer: andreas.nuessing@uni-muenster.de
#depending on
Depends: dune-common (>= 2.6) dune-grid (>= 2.6) dune-istl (>= 2.6) dune-pdelab (>= 2.6)
Suggests: dune-udg dune-subgrid dune-mc dune-uggrid (>= 2.6)
